from PyQt5 import QtCore, QtGui, QtWidgets


class UiLoginWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(UiLoginWindow, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LoginWindow")
        MainWindow.resize(904, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(904, 637))
        MainWindow.setMaximumSize(QtCore.QSize(904, 637))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(904, 637))
        self.centralwidget.setMaximumSize(QtCore.QSize(904, 637))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setAutoFillBackground(False)
        self.MainFrame.setStyleSheet(".QFrame{\n"
"background-color: rgb(203, 232, 238);\n"
"\n"
"}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setMidLineWidth(2)
        self.MainFrame.setObjectName("MainFrame")
        self.FrameLogo = QtWidgets.QFrame(self.MainFrame)
        self.FrameLogo.setGeometry(QtCore.QRect(0, 44, 265, 55))
        self.FrameLogo.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(185, 225, 233)\n"
"}")
        self.FrameLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameLogo.setObjectName("FrameLogo")
        self.label_brightgoal = QtWidgets.QLabel(self.FrameLogo)
        self.label_brightgoal.setGeometry(QtCore.QRect(100, 10, 117, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal.setFont(font)
        self.label_brightgoal.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_brightgoal.setObjectName("label_brightgoal")
        self.label_logo = QtWidgets.QLabel(self.FrameLogo)
        self.label_logo.setGeometry(QtCore.QRect(62, 12, 33, 33))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("Interface Assets/Brightgoal logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.label_heading_1 = QtWidgets.QLabel(self.MainFrame)
        self.label_heading_1.setGeometry(QtCore.QRect(68, 134, 397, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(17)
        self.label_heading_1.setFont(font)
        self.label_heading_1.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_heading_1.setObjectName("label_heading_1")
        self.label_instruction_1 = QtWidgets.QLabel(self.MainFrame)
        self.label_instruction_1.setGeometry(QtCore.QRect(70, 180, 397, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(11)
        self.label_instruction_1.setFont(font)
        self.label_instruction_1.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_instruction_1.setObjectName("label_instruction_1")
        self.label_instruction_2 = QtWidgets.QLabel(self.MainFrame)
        self.label_instruction_2.setGeometry(QtCore.QRect(68, 214, 397, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_instruction_2.setFont(font)
        self.label_instruction_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_instruction_2.setObjectName("label_instruction_2")
        self.label_instruction_3 = QtWidgets.QLabel(self.MainFrame)
        self.label_instruction_3.setGeometry(QtCore.QRect(66, 248, 397, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(11)
        self.label_instruction_3.setFont(font)
        self.label_instruction_3.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_instruction_3.setObjectName("label_instruction_3")
        self.FrameQrCode = QtWidgets.QFrame(self.MainFrame)
        self.FrameQrCode.setGeometry(QtCore.QRect(594, 120, 250, 250))
        self.FrameQrCode.setStyleSheet("QFrame{\n"
"    border-radius:125px;\n"
"    border: 2px solid rgb(1, 113, 135);\n"
"    background-color: rgb(103, 170, 183);\n"
"}")
        self.FrameQrCode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameQrCode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameQrCode.setObjectName("FrameQrCode")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FrameQrCode)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_qr_code = QtWidgets.QLabel(self.FrameQrCode)
        self.label_qr_code.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    background-color: none;\n"
"    margin: 35px;\n"
"}")
        self.label_qr_code.setText("")
        self.label_qr_code.setPixmap(QtGui.QPixmap("Interface Assets/qr_code.png"))
        self.label_qr_code.setScaledContents(True)
        self.label_qr_code.setIndent(-1)
        self.label_qr_code.setObjectName("label_qr_code")
        self.horizontalLayout_2.addWidget(self.label_qr_code)
        self.label_instruction_4 = QtWidgets.QLabel(self.MainFrame)
        self.label_instruction_4.setGeometry(QtCore.QRect(64, 318, 173, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(10)
        self.label_instruction_4.setFont(font)
        self.label_instruction_4.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_instruction_4.setObjectName("label_instruction_4")
        self.label_heading_2 = QtWidgets.QLabel(self.MainFrame)
        self.label_heading_2.setGeometry(QtCore.QRect(62, 386, 173, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(10)
        self.label_heading_2.setFont(font)
        self.label_heading_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_heading_2.setObjectName("label_heading_2")
        self.label_privacy_policy = QtWidgets.QLabel(self.MainFrame)
        self.label_privacy_policy.setGeometry(QtCore.QRect(60, 420, 795, 137))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(10)
        self.label_privacy_policy.setFont(font)
        self.label_privacy_policy.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"}")
        self.label_privacy_policy.setWordWrap(True)
        self.label_privacy_policy.setObjectName("label_privacy_policy")
        self.accept_privacy_policy = QtWidgets.QCheckBox(self.MainFrame)
        self.accept_privacy_policy.setGeometry(QtCore.QRect(60, 566, 161, 17))
        self.accept_privacy_policy.setObjectName("accept_privacy_policy")
        self.horizontalLayout.addWidget(self.MainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brightgoal"))
        self.label_brightgoal.setText(_translate("MainWindow", "Brightgoal"))
        self.label_heading_1.setText(_translate("MainWindow", "To use WhatsApp on your Computer"))
        self.label_instruction_1.setText(_translate("MainWindow", "1. Open WhatsApp on your phone"))
        self.label_instruction_2.setText(_translate("MainWindow", "2. Tap on \'Menu\' or \'Setting\' and Select \'Linked Devices\'"))
        self.label_instruction_3.setText(_translate("MainWindow", "3. Point your phone to this screen to caputer the code"))
        self.label_instruction_4.setText(_translate("MainWindow", "Need help to get started?"))
        self.label_heading_2.setText(_translate("MainWindow", "Privacy and Policy"))
        self.label_privacy_policy.setText(_translate("MainWindow", "This software is developed to automate Whatsapp and make your work easier, this pack provides lots of features to do things even faster than normal only for genuine use\n"
"if your using the application to perform unwanted activities we won’t be responsible for this.\n"
"whatever you are doing using this application ensure that it won’t cause you any problem, otherwise will be responsible for it on your own.\n"
"Thanks for using our Application, visit www.brightgoal.com for more information.\n"
"developed by Harvindar Singh"))
        self.accept_privacy_policy.setText(_translate("MainWindow", "Accept Privacy and Policy"))


class UiLoadingWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(UiLoadingWindow, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 290)
        MainWindow.setMinimumSize(QtCore.QSize(732, 290))
        MainWindow.setMaximumSize(QtCore.QSize(732, 290))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.83, y2:0.648, stop:0.00568182 rgba(185, 225, 233, 255), stop:0.494318 rgba(124, 208, 221, 255), stop:1 rgba(185, 225, 233, 255));")
        MainWindow.setAnimated(True)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(326, 42, 80, 80))
        self.label_logo.setStyleSheet("background-color: none;")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("D:\\Python Project\\whatsapp-automation-master\\GUI\\../../../../../Downloads/Brightgoal logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.label_brightgoal = QtWidgets.QLabel(self.centralwidget)
        self.label_brightgoal.setGeometry(QtCore.QRect(292, 106, 159, 55))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal.setFont(font)
        self.label_brightgoal.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"    background-color: none;\n"
"}")
        self.label_brightgoal.setObjectName("label_brightgoal")
        self.label_brightgoal_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_brightgoal_2.setGeometry(QtCore.QRect(304, 150, 129, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal_2.setFont(font)
        self.label_brightgoal_2.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"background-color: none;\n"
"}")
        self.label_brightgoal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_brightgoal_2.setObjectName("label_brightgoal_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(108, 214, 527, 6))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color: #fff;\n"
"    background-color: rgb(0, 93, 112);\n"
"    border-style: none;\n"
"    border-radius: 3px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.085, x2:1, y2:0.438, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(4, 195, 247, 255), stop:1 rgba(238, 83, 150, 255));\n"
"    border-radius: 3px;\n"
"}")
        self.progressBar.setProperty("value", 40)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_brightgoal_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_brightgoal_3.setGeometry(QtCore.QRect(270, 234, 195, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal_3.setFont(font)
        self.label_brightgoal_3.setStyleSheet("QLabel{\n"
"    color: rgb(0, 93, 112);\n"
"background-color: none;\n"
"}")
        self.label_brightgoal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_brightgoal_3.setObjectName("label_brightgoal_3")
        self.FrameLogo = QtWidgets.QFrame(self.centralwidget)
        self.FrameLogo.setGeometry(QtCore.QRect(640, -34, 55, 101))
        self.FrameLogo.setStyleSheet("QFrame{\n"
"    border-radius: 27px;\n"
"    background-color: rgb(185, 225, 233);\n"
"}")
        self.FrameLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameLogo.setObjectName("FrameLogo")
        self.label_logo_2 = QtWidgets.QLabel(self.FrameLogo)
        self.label_logo_2.setGeometry(QtCore.QRect(14, 54, 30, 30))
        self.label_logo_2.setStyleSheet("background-color: none;")
        self.label_logo_2.setText("")
        self.label_logo_2.setPixmap(QtGui.QPixmap("D:/Python Project/whatsapp-automation-master/GUI/icon/whatsapp.png"))
        self.label_logo_2.setScaledContents(True)
        self.label_logo_2.setObjectName("label_logo_2")
        self.label_brightgoal.raise_()
        self.label_brightgoal_2.raise_()
        self.progressBar.raise_()
        self.label_logo.raise_()
        self.label_brightgoal_3.raise_()
        self.FrameLogo.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_brightgoal.setText(_translate("MainWindow", "Brightgoal"))
        self.label_brightgoal_2.setText(_translate("MainWindow", "Harvindar Singh"))
        self.label_brightgoal_3.setText(_translate("MainWindow", "Loading <b>Contact</b>"))


class UiMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(UiMainWindow, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
                                 " background-color: rgb(242, 242, 242);\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(959, 51))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 51))
        self.frame_2.setStyleSheet("QFrame{\n"
                                   "    background-color: rgb(185, 225, 233);\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(160, 31))
        self.frame_3.setMaximumSize(QtCore.QSize(160, 32))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.label_brightgoal = QtWidgets.QLabel(self.frame_3)
        self.label_brightgoal.setGeometry(QtCore.QRect(58, 0, 97, 27))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal.setFont(font)
        self.label_brightgoal.setStyleSheet("QLabel{\n"
                                            "    color: rgb(0, 93, 112);\n"
                                            "}")
        self.label_brightgoal.setObjectName("label_brightgoal")
        self.label_logo = QtWidgets.QLabel(self.frame_3)
        self.label_logo.setGeometry(QtCore.QRect(26, 2, 28, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_logo.setFont(font)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(
            "D:\\Python Project\\whatsapp-automation-master\\GUI\\../../../Downloads/Brightgoal logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_brightgoal_2 = QtWidgets.QLabel(self.frame_2)
        self.label_brightgoal_2.setMinimumSize(QtCore.QSize(197, 0))
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal_2.setFont(font)
        self.label_brightgoal_2.setStyleSheet("QLabel{\n"
                                              "    color: rgb(0, 93, 112);\n"
                                              "}")
        self.label_brightgoal_2.setObjectName("label_brightgoal_2")
        self.horizontalLayout_2.addWidget(self.label_brightgoal_2)
        spacerItem1 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setStyleSheet("border: none;\n"
                                      "color: rgb(1, 111, 135);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Python Project\\whatsapp-automation-master\\GUI\\icon/ci_menu-alt-02.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(962, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(285, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(285, 16777215))
        self.frame_5.setStyleSheet("background-color: rgb(224, 224, 224);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setEnabled(True)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_9.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame_9.setFont(font)
        self.frame_9.setStyleSheet("background-color:rgb(228, 198, 198);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setContentsMargins(9, 5, 5, -1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        self.label_2.setMinimumSize(QtCore.QSize(45, 45))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\Python Project\\whatsapp-automation-master\\GUI\\icon/warning.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 57))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 57))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_brightgoal_5 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal_5.setFont(font)
        self.label_brightgoal_5.setStyleSheet("QLabel{\n"
                                              "    color: #000;\n"
                                              "}")
        self.label_brightgoal_5.setObjectName("label_brightgoal_5")
        self.verticalLayout_4.addWidget(self.label_brightgoal_5)
        self.label_brightgoal_6 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_brightgoal_6.setFont(font)
        self.label_brightgoal_6.setStyleSheet("QLabel{\n"
                                              "    color: #000;\n"
                                              "}")
        self.label_brightgoal_6.setWordWrap(True)
        self.label_brightgoal_6.setObjectName("label_brightgoal_6")
        self.verticalLayout_4.addWidget(self.label_brightgoal_6)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_7.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(9, 5, 5, -1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.profile_picture = QtWidgets.QLabel(self.frame_7)
        self.profile_picture.setMinimumSize(QtCore.QSize(40, 40))
        self.profile_picture.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.profile_picture.setFont(font)
        self.profile_picture.setStyleSheet("border-radius: 5px;")
        self.profile_picture.setText("")
        self.profile_picture.setPixmap(
            QtGui.QPixmap("D:\\Python Project\\whatsapp-automation-master\\GUI\\icon/man.png"))
        self.profile_picture.setScaledContents(True)
        self.profile_picture.setObjectName("profile_picture")
        self.horizontalLayout_4.addWidget(self.profile_picture)
        self.profile_name = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.profile_name.setFont(font)
        self.profile_name.setStyleSheet("QLabel{\n"
                                        "    color: rgb(0, 93, 112);\n"
                                        "}")
        self.profile_name.setObjectName("profile_name")
        self.horizontalLayout_4.addWidget(self.profile_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setStyleSheet("border: none;\n"
                                        "color: rgb(1, 111, 135);")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_8.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame_8.setFont(font)
        self.frame_8.setStyleSheet("background-color: rgb(215, 219, 220);\n"
                                   "")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 34))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 34))
        self.frame_11.setStyleSheet("border: 1px solid rgb(1, 111, 135);\n"
                                    "border-radius: 5px;\n"
                                    "")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setMinimumSize(QtCore.QSize(18, 18))
        self.label_3.setMaximumSize(QtCore.QSize(18, 18))
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Python Project\\whatsapp-automation-master\\GUI\\icon/User.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setStyleSheet("border: none;\n"
                                    "background-color: #0000000;\n"
                                    "")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_3.setStyleSheet("border: none;\n"
                                        "color: rgb(1, 111, 135);")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Python Project\\whatsapp-automation-master\\GUI\\icon/close.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.checkBox = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox.setStyleSheet("QCheckBox{\n"
                                    "    border: none;\n"
                                    "}\n"
                                    "QCheckBox::indicator{\n"
                                    "    width: 28px;\n"
                                    "    height: 28px;\n"
                                    "    \n"
                                    "}")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea.setStyleSheet("border: 0px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 283, 360))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setGeometry(QtCore.QRect(18, 12, 565, 297))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setStyleSheet("margin-bottom: 3px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profile_name_2 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.profile_name_2.setFont(font)
        self.profile_name_2.setStyleSheet("QLabel{\n"
                                          "    color: rgb(0, 93, 112);\n"
                                          "}")
        self.profile_name_2.setObjectName("profile_name_2")
        self.horizontalLayout.addWidget(self.profile_name_2)
        spacerItem3 = QtWidgets.QSpacerItem(489, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frame_13)
        self.type_message = QtWidgets.QTextEdit(self.frame_12)
        self.type_message.setStyleSheet("background-color: #fff;\n"
                                        "color: rgb(1, 113, 135);\n"
                                        "border :1px solid rgb(121, 177, 188);\n"
                                        "border-top-left-radius :5px;\n"
                                        "border-top-right-radius : 5px; \n"
                                        "border-bottom-left-radius : 0px; \n"
                                        "border-bottom-right-radius : 0px")
        self.type_message.setObjectName("type_message")
        self.verticalLayout_3.addWidget(self.type_message)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setStyleSheet("background-color: rgb(186, 212, 217);\n"
                                    "border :0px;\n"
                                    "border-top-left-radius : 0px;\n"
                                    "border-top-right-radius : 0px; \n"
                                    "border-bottom-left-radius : 5px; \n"
                                    "border-bottom-right-radius : 5px")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_4.setStyleSheet("border: none;\n"
                                        "color: rgb(1, 111, 135);")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(50, 22))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: #fff;\n"
                                      "border-style: none;\n"
                                      "color: rgb(1, 113, 135);\n"
                                      "border-radius: 3px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.profile_name_3 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.profile_name_3.setFont(font)
        self.profile_name_3.setStyleSheet("QLabel{\n"
                                          "    color: rgb(0, 93, 112);\n"
                                          "    margin-left: 15px;\n"
                                          "}")
        self.profile_name_3.setObjectName("profile_name_3")
        self.horizontalLayout_8.addWidget(self.profile_name_3)
        spacerItem4 = QtWidgets.QSpacerItem(177, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.show_seleted_media = QtWidgets.QPushButton(self.frame_14)
        self.show_seleted_media.setStyleSheet("border: none;\n"
                                              "color: rgb(1, 111, 135);")
        self.show_seleted_media.setText("")
        self.show_seleted_media.setIcon(icon)
        self.show_seleted_media.setIconSize(QtCore.QSize(25, 30))
        self.show_seleted_media.setObjectName("show_seleted_media")
        self.horizontalLayout_8.addWidget(self.show_seleted_media)
        self.show_emoji = QtWidgets.QPushButton(self.frame_14)
        self.show_emoji.setStyleSheet("border: none;\n"
                                      "color: rgb(1, 111, 135);")
        self.show_emoji.setText("")
        self.show_emoji.setIcon(icon)
        self.show_emoji.setIconSize(QtCore.QSize(25, 30))
        self.show_emoji.setObjectName("show_emoji")
        self.horizontalLayout_8.addWidget(self.show_emoji)
        self.bold = QtWidgets.QPushButton(self.frame_14)
        self.bold.setStyleSheet("border: none;\n"
                                "color: rgb(1, 111, 135);")
        self.bold.setText("")
        self.bold.setIcon(icon)
        self.bold.setIconSize(QtCore.QSize(25, 30))
        self.bold.setObjectName("bold")
        self.horizontalLayout_8.addWidget(self.bold)
        self.italic = QtWidgets.QPushButton(self.frame_14)
        self.italic.setStyleSheet("border: none;\n"
                                  "color: rgb(1, 111, 135);")
        self.italic.setText("")
        self.italic.setIcon(icon)
        self.italic.setIconSize(QtCore.QSize(25, 30))
        self.italic.setObjectName("italic")
        self.horizontalLayout_8.addWidget(self.italic)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_9.setStyleSheet("border: none;\n"
                                        "color: rgb(1, 111, 135);")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.monoscape = QtWidgets.QPushButton(self.frame_14)
        self.monoscape.setStyleSheet("border: none;\n"
                                     "color: rgb(1, 111, 135);")
        self.monoscape.setText("")
        self.monoscape.setIcon(icon)
        self.monoscape.setIconSize(QtCore.QSize(25, 30))
        self.monoscape.setObjectName("monoscape")
        self.horizontalLayout_8.addWidget(self.monoscape)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_6)
        self.frame_15.setGeometry(QtCore.QRect(592, 38, 53, 511))
        self.frame_15.setStyleSheet("QPushButton{\n"
                                    "    border: none;\n"
                                    "    color: rgb(1, 111, 135);\n"
                                    "    background-color: rgb(1, 113, 135);\n"
                                    "    border-radius: 16px;\n"
                                    "}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_18.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_18.setStyleSheet("")
        self.pushButton_18.setText("")
        self.pushButton_18.setIcon(icon)
        self.pushButton_18.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_6.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_19.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_19.setStyleSheet("border: none;\n"
                                         "color: rgb(1, 111, 135);")
        self.pushButton_19.setText("")
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_6.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_20.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_20.setStyleSheet("border: none;\n"
                                         "color: rgb(1, 111, 135);")
        self.pushButton_20.setText("")
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_6.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_21.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_21.setStyleSheet("border: none;\n"
                                         "color: rgb(1, 111, 135);")
        self.pushButton_21.setText("")
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_6.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_22.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_22.setStyleSheet("border: none;\n"
                                         "color: rgb(1, 111, 135);")
        self.pushButton_22.setText("")
        self.pushButton_22.setIcon(icon)
        self.pushButton_22.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_6.addWidget(self.pushButton_22)
        spacerItem5 = QtWidgets.QSpacerItem(20, 254, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_28.setMinimumSize(QtCore.QSize(33, 33))
        self.pushButton_28.setStyleSheet("border: none;\n"
                                         "color: rgb(1, 111, 135);")
        self.pushButton_28.setText("")
        self.pushButton_28.setIcon(icon)
        self.pushButton_28.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_6.addWidget(self.pushButton_28)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_brightgoal.setText(_translate("MainWindow", "Brightgoal"))
        self.label_brightgoal_2.setText(_translate("MainWindow", "WhatsApp"))
        self.label_brightgoal_5.setText(_translate("MainWindow", "Computer not connected"))
        self.label_brightgoal_6.setText(
            _translate("MainWindow", "Make sure you computer has an active internet connection"))
        self.profile_name.setText(_translate("MainWindow", "Harvindar Singh"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.profile_name_2.setText(_translate("MainWindow", "Message"))
        self.type_message.setPlaceholderText(_translate("MainWindow", "Type your message here"))
        self.profile_name_3.setText(_translate("MainWindow", "W 100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = UiLoginWindow()

    MainWindow.show()
    sys.exit(app.exec_())
